[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[colors.bright]
black = "#1e1c31"
blue = "#78a8ff"
cyan = "#63f2f1"
green = "#7fe9c3"
magenta = "#7676ff"
red = "#f02e6e"
white = "#8a889d"
yellow = "#f2b482"

[colors.normal]
black = "#1e1c31"
blue = "#91ddff"
cyan = "#abf8f7"
green = "#a1efd3"
magenta = "#d4bfff"
red = "#f48fb1"
white = "#cbe3e7"
yellow = "#ffe6b3"

[colors.primary]
background = "#1e1c31"
foreground = "#cbe3e7"

[font]
size = 8.4

[font.bold]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 50000

[window]
opacity = 0.8

[window.padding]
x = 8
y = 8

[keyboard]
